// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package cms

import (
	"github.com/deslee/cms/database/models"
)

type GenericResult struct {
	ErrorMessage *string `json:"errorMessage"`
	Success      bool    `json:"success"`
}

type ItemInput struct {
	ID     *string  `json:"id"`
	Type   string   `json:"type"`
	Data   string   `json:"data"`
	Groups []string `json:"groups"`
}

type ItemResult struct {
	Data         *models.Item `json:"data"`
	ErrorMessage *string      `json:"errorMessage"`
	Success      bool         `json:"success"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResult struct {
	Data         *models.User `json:"data"`
	ErrorMessage *string      `json:"errorMessage"`
	Success      bool         `json:"success"`
	Token        *string      `json:"token"`
}

type RegisterInput struct {
	Email    string `json:"email"`
	Data     string `json:"data"`
	Password string `json:"password"`
}

type SiteInput struct {
	ID   *string `json:"id"`
	Name string  `json:"name"`
	Data string  `json:"data"`
}

type SiteResult struct {
	Data         *models.Site `json:"data"`
	ErrorMessage *string      `json:"errorMessage"`
	Success      bool         `json:"success"`
}

type UserInput struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Data  string `json:"data"`
}

type UserResult struct {
	Data         *models.User `json:"data"`
	ErrorMessage *string      `json:"errorMessage"`
	Success      bool         `json:"success"`
}
